# Generated by Django 3.0.4 on 2020-03-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rainfall',
            name='amount',
            field=models.FloatField(),
        ),
    ]
